-- 코드를 입력하세요
-- '세단' 또는 'SUV' 인 자동차 중 - 해결
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 - 해결
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
SELECT A.CAR_ID, A.CAR_TYPE,
       ROUND(A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
  ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
  AND C.DURATION_TYPE = '30일 이상'
  AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE B.CAR_ID = A.CAR_ID
          AND B.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
          AND B.END_DATE   >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
  )
  AND (A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE/100))
      BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;