SELECT A.CAR_ID, A.CAR_TYPE,
    A.DAILY_FEE * (1-C.DISCOUNT_RATE/100)*30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단','SUV')
AND C.DURATION_TYPE = '30일 이상'
AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE A.CAR_ID = B.CAR_ID
    AND START_DATE <= TO_DATE('2022-11-30','YYYY-MM-DD')
    AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
)
AND A.DAILY_FEE * (1-C.DISCOUNT_RATE/100)*30 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC