SELECT 
    UGU.USER_ID AS USER_ID, 
    UGU.NICKNAME AS NICKNAME, 
    (UGU.CITY || ' ' || UGU.STREET_ADDRESS1 || ' ' || UGU.STREET_ADDRESS2) AS 전체주소,
    (SUBSTR(UGU.TLNO,1,3) || '-' || SUBSTR(UGU.TLNO,4,4) || '-' || SUBSTR(UGU.TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER UGU
JOIN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
) B ON UGU.USER_ID = B.WRITER_ID
ORDER BY UGU.USER_ID DESC;