SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR,
       TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM'))  AS MONTH,
       U.GENDER,
       COUNT(DISTINCT U.USER_ID)     AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
  ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'),
         TO_CHAR(O.SALES_DATE, 'MM'),
         U.GENDER
ORDER BY YEAR, MONTH, U.GENDER;