-- 코드를 입력하세요

SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(O.SALES_DATE,'MM')) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021'),1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE TO_CHAR(U.JOINED,'YYYY') = '2021'
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(O.SALES_DATE,'MM'))
ORDER BY YEAR, MONTH