SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR,
       TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH,
       COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
       ROUND(
         COUNT(DISTINCT S.USER_ID) /
         (SELECT COUNT(*) 
          FROM USER_INFO 
          WHERE TO_CHAR(JOINED,'YYYY')='2021')
       , 1) AS PURCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U
  ON S.USER_ID = U.USER_ID
 AND TO_CHAR(U.JOINED,'YYYY')='2021'
GROUP BY TO_CHAR(S.SALES_DATE,'YYYY'),
         TO_NUMBER(TO_CHAR(S.SALES_DATE,'MM'))
ORDER BY YEAR, MONTH;