-- 코드를 입력하세요

-- 2021년에 가입한 회원 중 상품을 구매한 회원수
SELECT TO_CHAR(O.SALES_DATE,'YYYY') AS YEAR,
        TO_NUMBER(TO_CHAR(O.SALES_DATE,'MM')) AS MONTH,
        COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021'), 1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
AND TO_CHAR(U.JOINED,'YYYY') = '2021'
GROUP BY TO_CHAR(O.SALES_DATE,'YYYY'),TO_NUMBER(TO_CHAR(O.SALES_DATE,'MM'))
ORDER BY YEAR, MONTH


