-- 코드를 입력하세요
--  입양을 못 간 동물 중
-- 가장 오래 보호소에 있었던 동물 3마리
-- 이름과 보호 시작일
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN  (
    SELECT AI.ANIMAL_ID
    FROM ANIMAL_INS AI
    JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
)
ORDER BY DATETIME
FETCH FIRST 3 ROWS ONLY;
