-- 코드를 입력하세요
SELECT F.PRODUCT_ID, F.PRODUCT_NAME, SUM(F.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT F
JOIN FOOD_ORDER O
ON F.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(O.PRODUCE_DATE,'YYYY-MM') = '2022-05'
GROUP BY F.PRODUCT_ID, F.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID ASC