SELECT H.HISTORY_ID,
       (H.END_DATE - H.START_DATE + 1) * C.DAILY_FEE *
       (1 - NVL(P.DISCOUNT_RATE, 0)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON C.CAR_TYPE = P.CAR_TYPE
 AND (
        (H.END_DATE - H.START_DATE + 1) >= 90 AND P.DURATION_TYPE = '90일 이상'
     OR (H.END_DATE - H.START_DATE + 1) BETWEEN 30 AND 89 AND P.DURATION_TYPE = '30일 이상'
     OR (H.END_DATE - H.START_DATE + 1) BETWEEN 7  AND 29 AND P.DURATION_TYPE = '7일 이상'
     )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;