-- 코드를 입력하세요
-- 7월 아이스크림 총 주문량
-- 상반기의 아이스크림 총 주문량
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN JULY J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY

-- SELECT *
-- FROM FIRST_HALF F
-- JOIN JULY J
-- ON F.FLAVOR = J.FLAVOR