-- 코드를 입력하세요

WITH HOURS AS (
    SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)

SELECT HO.HOUR, NVL(H.COUNT, 0) AS COUNT
FROM HOURS HO
LEFT JOIN (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
) H
ON H.HOUR = HO.HOUR
ORDER BY HOUR