-- 코드를 입력하세요
WITH HOURS AS (
    SELECT LEVEL-1 AS HOUR 
    FROM DUAL 
    CONNECT BY LEVEL<= 24
)



SELECT HH.HOUR, NVL(H.COUNT, 0) AS COUNT
FROM HOURS HH
LEFT JOIN (
    SELECT TO_CHAR(DATETIME,'HH24') AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY TO_CHAR(DATETIME,'HH24')
) H
ON HH.HOUR = H.HOUR
ORDER BY HH.HOUR