-- 코드를 입력하세요
WITH HOURS AS (
    SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)

SELECT H.HOUR, NVL(HH.COUNT,0) AS COUNT
FROM HOURS H
LEFT JOIN (
    SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS A
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))    
) HH
ON H.HOUR = HH.HOUR
ORDER BY H.HOUR