-- 코드를 입력하세요
-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람
SELECT UGU.USER_ID, UGU.NICKNAME, B.TOTAL_PRICE
FROM USED_GOODS_USER UGU
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000 
    ) B
ON UGU.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_PRICE ASC
    
