-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR, COUNT(TO_CHAR(DATETIME,'HH24')) AS COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME,'HH24')
HAVING TO_CHAR(DATETIME,'HH24') >= 09
AND TO_CHAR(DATETIME,'HH24') <= 19
ORDER BY HOUR ASC

