-- 코드를 입력하세요
-- 리뷰를 가장 많이 작성한 회원의 리뷰

WITH REVIEW AS (
    SELECT M.MEMBER_ID, M.MEMBER_NAME
    FROM MEMBER_PROFILE M
    JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
    GROUP BY M.MEMBER_ID, M.MEMBER_NAME
    HAVING COUNT(M.MEMBER_ID) = (
        SELECT MAX(COUNT(MEMBER_ID))
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )
)

SELECT R.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN REVIEW R
ON R.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT


