-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(START_DATE,'MM')) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) 
AND START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
GROUP BY CAR_ID, TO_NUMBER(TO_CHAR(START_DATE,'MM'))
HAVING COUNT(CAR_ID) > 0
ORDER BY MONTH, CAR_ID DESC

