-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
ON C.CAR_ID = R.CAR_ID
WHERE C.CAR_TYPE = '세단'
GROUP BY C.CAR_ID
HAVING MAX(TO_CHAR(R.START_DATE,'MM')) = '10'
ORDER BY C.CAR_ID DESC