-- 코드를 입력하세요
-- 대여 중인 자동차들의 정보를 담은 CAR_RENTAL_COMPANY_CAR
-- 테이블과 자동차 대여 기록 정보를 담은 CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- 자동차 종류가 '세단'인 자동차 && 10월에 대여를 시작한 기록이 있는 자동차 ID 

SELECT DISTINCT CRCR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCR.CAR_ID = CRCRH.CAR_ID
WHERE CRCR.CAR_TYPE = '세단'
AND SUBSTR(TO_CHAR(CRCRH.START_DATE),4,3) = 'OCT'
ORDER BY CAR_ID DESC
