-- 코드를 입력하세요
-- SELECT VIEWS
-- FROM USED_GOODS_BOARD UGB 
-- INNER JOIN USED_GOODS_FILE UGF
-- ON UGB.BOARD_ID = UGF.BOARD_ID
-- WHERE ROWNUM = 1
-- ORDER BY VIEWS DESC
SELECT ('/home/grep/src/' || BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (
    SELECT BOARD_ID
    FROM  
    (SELECT BOARD_ID
    FROM USED_GOODS_BOARD 
    ORDER BY VIEWS DESC
    )   
    WHERE ROWNUM = 1
)
ORDER BY FILE_ID DESC

-- 조회수가 가장 높은 중고거래 게시물
