-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) M
ON F.CATEGORY = M.CATEGORY
AND F.PRICE = M.MAX_PRICE
AND (F.CATEGORY = '과자' OR F.CATEGORY = '국' OR F.CATEGORY = '김치' OR F.CATEGORY = '식용유')
ORDER BY M.MAX_PRICE DESC